import { useState } from 'react';
import type { DealSummaryResponse } from '@/types';
import {
  IconCheckCircle,
  IconExclamationTriangle,
  IconDocumentText,
  IconSparkles,
  IconClipboard,
  IconCheck,
  IconArrowDownTray,
  IconShieldCheck,
} from '../icons';

interface Props {
  summary: DealSummaryResponse | null;
  loading?: boolean;
}

export function SummaryPanel({ summary, loading }: Props) {
  const [copied, setCopied] = useState(false);
  const [showBriefModal, setShowBriefModal] = useState(false);

  if (loading || !summary) {
    return (
      <div className="card p-6 animate-pulse space-y-4">
        <div className="h-4 bg-slate-200 rounded w-1/3"></div>
        <div className="h-16 bg-slate-100 rounded"></div>
        <div className="h-32 bg-slate-100 rounded"></div>
      </div>
    );
  }

  // Calculate Transaction Health Score (0 - 100)
  const totalDeadlines = summary.contingencyMatrix.length;
  const confirmedCount = summary.contingencyMatrix.filter((c) => c.isConfirmed).length;
  const highRiskCount = summary.riskMatrix.filter((r) => r.severity === 'high').length;
  const medRiskCount = summary.riskMatrix.filter((r) => r.severity === 'medium').length;

  let healthScore = 100;
  if (totalDeadlines > 0) {
    healthScore -= (totalDeadlines - confirmedCount) * 8;
  }
  healthScore -= highRiskCount * 15;
  healthScore -= medRiskCount * 5;
  healthScore = Math.max(20, Math.min(100, healthScore));

  const strokeDashoffset = 251.2 - (251.2 * healthScore) / 100;
  const gaugeColor =
    healthScore >= 80 ? 'text-emerald-600' : healthScore >= 60 ? 'text-amber-500' : 'text-rose-500';

  const generateMarkdownBrief = () => {
    return `# TRANSACTION EXECUTIVE BRIEF
**Property Address:** ${summary.keyEntities.propertyAddress}
**Contract Acceptance Date:** ${summary.keyEntities.acceptanceDate || 'Pending'}
**Buyer:** ${summary.keyEntities.buyerName || 'Unspecified'} | **Seller:** ${summary.keyEntities.sellerName || 'Unspecified'}
**Transaction Health Score:** ${healthScore}/100

---

## 📅 CONTINGENCY DEADLINE SCHEDULE
${summary.contingencyMatrix
  .map(
    (c) =>
      `- **${c.label}**: ${c.targetDate} (${c.isConfirmed ? 'Confirmed' : 'Pending Review'})${
        c.sourceDocument ? ` — Source: ${c.sourceDocument}${c.pageNumber ? ` (P.${c.pageNumber})` : ''}` : ''
      }`
  )
  .join('\n')}

---

## ⚠️ RISK MATRIX & ACTION ITEMS
${
  summary.riskMatrix.length > 0
    ? summary.riskMatrix.map((r) => `- [${r.severity.toUpperCase()}] **${r.title}**: ${r.description}`).join('\n')
    : 'No critical contract conflicts detected.'
}

---
*Generated by Contingency Copilot AI Knowledge Assistant on ${new Date().toLocaleDateString()}*
`;
  };

  const handleCopyBrief = () => {
    const text = generateMarkdownBrief();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadBrief = () => {
    const text = generateMarkdownBrief();
    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Executive_Brief_${summary.keyEntities.propertyAddress.replace(/[^a-zA-Z0-9]/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      {/* Top Health Gauge & Action Bar */}
      <div className="flex items-center justify-between gap-3 p-4 bg-white rounded-2xl border border-slate-200/90 shadow-2xs">
        <div className="flex items-center gap-3.5">
          {/* Circular SVG Progress Gauge */}
          <div className="relative flex h-14 w-14 items-center justify-center shrink-0">
            <svg className="h-14 w-14 -rotate-90 transform" viewBox="0 0 90 90">
              <circle
                cx="45"
                cy="45"
                r="38"
                stroke="currentColor"
                strokeWidth="7"
                fill="transparent"
                className="text-slate-100"
              />
              <circle
                cx="45"
                cy="45"
                r="38"
                stroke="currentColor"
                strokeWidth="7"
                fill="transparent"
                strokeDasharray="238.7"
                strokeDashoffset={238.7 - (238.7 * healthScore) / 100}
                strokeLinecap="round"
                className={`${gaugeColor} transition-all duration-700 ease-out`}
              />
            </svg>
            <div className="absolute flex flex-col items-center justify-center text-center">
              <span className="text-xs font-black tracking-tight text-slate-900 leading-none font-mono">
                {healthScore}
              </span>
              <span className="text-[8px] font-bold text-slate-400 uppercase tracking-tighter mt-0.5">
                Score
              </span>
            </div>
          </div>

          <div>
            <div className="flex items-center gap-1.5">
              <h4 className="text-xs font-bold text-slate-900">
                Transaction Health Score
              </h4>
              <span className="inline-flex items-center gap-0.5 text-[10px] font-semibold text-emerald-700 bg-emerald-50 px-1.5 py-0.2 rounded border border-emerald-200">
                <IconShieldCheck className="h-2.5 w-2.5" />
                Audited
              </span>
            </div>
            <p className="text-[11px] text-slate-500 mt-0.5">
              {healthScore >= 80
                ? 'High compliance — low risk detected'
                : 'Attention needed on unverified terms'}
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={() => setShowBriefModal(true)}
          className="btn-secondary text-xs flex items-center gap-1.5 py-1.5 px-3 shrink-0"
        >
          <IconClipboard className="h-3.5 w-3.5 text-slate-500" />
          <span>Export Brief</span>
        </button>
      </div>

      {/* Executive Summary */}
      <div className="card p-4 border-brand-100/80 bg-gradient-to-br from-white via-brand-50/20 to-indigo-50/20 space-y-2">
        <div className="flex items-center gap-2">
          <div className="flex h-5 w-5 items-center justify-center rounded bg-brand-100 text-brand-700">
            <IconSparkles className="h-3.5 w-3.5" />
          </div>
          <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
            Executive Brief
          </h3>
        </div>
        <p className="text-xs leading-relaxed text-slate-700">
          {summary.executiveSummary}
        </p>
      </div>

      {/* Risk Matrix */}
      {summary.riskMatrix.length > 0 && (
        <div className="card p-4 space-y-3">
          <div className="flex items-center gap-2">
            <IconExclamationTriangle className="h-4 w-4 text-amber-500" />
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wide">
              Transaction Risks &amp; Action Items ({summary.riskMatrix.length})
            </h3>
          </div>

          <div className="space-y-2">
            {summary.riskMatrix.map((risk, idx) => (
              <div
                key={idx}
                className={`p-3 rounded-xl border text-xs ${
                  risk.severity === 'high'
                    ? 'border-rose-200 bg-rose-50/70 text-rose-950'
                    : 'border-amber-200 bg-amber-50/70 text-amber-950'
                }`}
              >
                <div className="flex items-center justify-between font-bold">
                  <span>{risk.title}</span>
                  <span className="text-[9px] uppercase tracking-wider font-extrabold px-1.5 py-0.5 rounded bg-white/80 border border-slate-200/60">
                    {risk.severity}
                  </span>
                </div>
                <p className="mt-1 text-slate-700 text-[11px] leading-relaxed">{risk.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Contingency Matrix */}
      <div className="card overflow-hidden">
        <div className="p-3.5 border-b border-slate-100 flex items-center justify-between">
          <div>
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wide">
              Contingency Deadlines ({summary.contingencyMatrix.length})
            </h3>
            <p className="text-[10px] text-slate-400">
              Deterministic schedule derived from contract acceptance date
            </p>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-600">
            <thead className="bg-slate-50/90 text-slate-700 border-b border-slate-100 text-[11px]">
              <tr>
                <th className="py-2.5 px-3.5 font-semibold">Contingency</th>
                <th className="py-2.5 px-3.5 font-semibold">Target Date</th>
                <th className="py-2.5 px-3.5 font-semibold">Source</th>
                <th className="py-2.5 px-3.5 font-semibold text-right">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {summary.contingencyMatrix.map((item, idx) => (
                <tr key={idx} className="hover:bg-slate-50/70 transition-colors">
                  <td className="py-2.5 px-3.5 font-semibold text-slate-900">{item.label}</td>
                  <td className="py-2.5 px-3.5 font-mono text-[11px] text-slate-800 font-medium">{item.targetDate}</td>
                  <td className="py-2.5 px-3.5 text-slate-500 truncate max-w-[140px] text-[11px]">
                    {item.sourceDocument ? (
                      <span>
                        {item.sourceDocument} {item.pageNumber ? `(P.${item.pageNumber})` : ''}
                      </span>
                    ) : (
                      '—'
                    )}
                  </td>
                  <td className="py-2.5 px-3.5 text-right">
                    {item.isConfirmed ? (
                      <span className="inline-flex items-center gap-1 text-emerald-700 font-semibold text-[10px] bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                        <IconCheckCircle className="h-3 w-3 text-emerald-600" />
                        Verified
                      </span>
                    ) : (
                      <span className="rounded-full bg-amber-50 px-2 py-0.5 text-amber-800 text-[10px] font-semibold border border-amber-200">
                        Pending
                      </span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Export Executive Brief Modal */}
      {showBriefModal && (
        <div className="fixed inset-0 z-50 bg-slate-950/60 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full overflow-hidden border border-slate-200 animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center justify-between px-5 py-4 border-b border-slate-100 bg-slate-50/80">
              <div className="flex items-center gap-2">
                <IconDocumentText className="h-5 w-5 text-brand-600" />
                <h3 className="text-sm font-bold text-slate-900">Executive Deal Brief</h3>
              </div>
              <button
                type="button"
                onClick={() => setShowBriefModal(false)}
                className="text-slate-400 hover:text-slate-700 text-lg leading-none cursor-pointer"
              >
                &times;
              </button>
            </div>

            <div className="p-5 space-y-4 max-h-[60vh] overflow-y-auto">
              <div className="p-3.5 bg-slate-900 text-slate-200 rounded-xl font-mono text-[11px] leading-relaxed whitespace-pre-wrap select-all">
                {generateMarkdownBrief()}
              </div>
            </div>

            <div className="flex items-center justify-between px-5 py-3.5 bg-slate-50 border-t border-slate-100">
              <span className="text-[11px] text-slate-400">Ready to share with client or escrow</span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleDownloadBrief}
                  className="btn-secondary text-xs flex items-center gap-1.5 py-1.5 px-3"
                >
                  <IconArrowDownTray className="h-3.5 w-3.5" />
                  <span>Download .md</span>
                </button>
                <button
                  type="button"
                  onClick={handleCopyBrief}
                  className="btn-primary text-xs flex items-center gap-1.5 py-1.5 px-3"
                >
                  {copied ? (
                    <>
                      <IconCheck className="h-3.5 w-3.5 text-white" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <IconClipboard className="h-3.5 w-3.5 text-white" />
                      <span>Copy Brief</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

