import { useState } from 'react';
import type { DealSummaryResponse } from '@/types';
import {
  CheckCircle2,
  AlertTriangle,
  FileText,
  Sparkles,
  Copy,
  Check,
  Download,
  ShieldCheck,
  X,
  Clock,
} from 'lucide-react';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';

interface Props {
  summary: DealSummaryResponse | null;
  loading?: boolean;
}

export function SummaryPanel({ summary, loading }: Props) {
  const [copied, setCopied] = useState(false);
  const [showBriefModal, setShowBriefModal] = useState(false);

  if (loading || !summary) {
    return (
      <div className="rounded-md border border-border bg-surface p-6 animate-pulse space-y-3">
        <div className="h-4 bg-secondary rounded w-1/3"></div>
        <div className="h-16 bg-secondary/60 rounded"></div>
        <div className="h-32 bg-secondary/60 rounded"></div>
      </div>
    );
  }

  // Calculate Transaction Health Score (0 - 100)
  const totalDeadlines = summary.contingencyMatrix.length;
  const confirmedCount = summary.contingencyMatrix.filter((c) => c.isConfirmed).length;
  const highRiskCount = summary.riskMatrix.filter((r) => r.severity === 'high').length;
  const medRiskCount = summary.riskMatrix.filter((r) => r.severity === 'medium').length;

  let healthScore = 100;
  if (totalDeadlines > 0) {
    healthScore -= (totalDeadlines - confirmedCount) * 8;
  }
  healthScore -= highRiskCount * 15;
  healthScore -= medRiskCount * 5;
  healthScore = Math.max(20, Math.min(100, healthScore));

  const gaugeColor =
    healthScore >= 80 ? 'text-success' : healthScore >= 60 ? 'text-warning' : 'text-danger';

  const generateMarkdownBrief = () => {
    return `# TRANSACTION EXECUTIVE BRIEF
**Property Address:** ${summary.keyEntities.propertyAddress}
**Contract Acceptance Date:** ${summary.keyEntities.acceptanceDate || 'Pending'}
**Buyer:** ${summary.keyEntities.buyerName || 'Unspecified'} | **Seller:** ${summary.keyEntities.sellerName || 'Unspecified'}
**Transaction Health Score:** ${healthScore}/100

---

## CONTINGENCY DEADLINE SCHEDULE
${summary.contingencyMatrix
  .map(
    (c) =>
      `- **${c.label}**: ${c.targetDate} (${c.isConfirmed ? 'Confirmed' : 'Pending Review'})${
        c.sourceDocument ? ` — Source: ${c.sourceDocument}${c.pageNumber ? ` (P.${c.pageNumber})` : ''}` : ''
      }`
  )
  .join('\n')}

---

## RISK MATRIX & ACTION ITEMS
${
  summary.riskMatrix.length > 0
    ? summary.riskMatrix.map((r) => `- [${r.severity.toUpperCase()}] **${r.title}**: ${r.description}`).join('\n')
    : 'No critical contract conflicts detected.'
}

---
*Generated by Contingency Copilot on ${new Date().toLocaleDateString()}*
`;
  };

  const handleCopyBrief = () => {
    const text = generateMarkdownBrief();
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadBrief = () => {
    const text = generateMarkdownBrief();
    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Executive_Brief_${summary.keyEntities.propertyAddress.replace(/[^a-zA-Z0-9]/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-4">
      {/* Top Health Gauge & Action Bar */}
      <div className="flex items-center justify-between gap-3 p-3.5 bg-surface rounded-md border border-border shadow-2xs">
        <div className="flex items-center gap-3">
          {/* Circular Progress Gauge */}
          <div className="relative flex h-12 w-12 items-center justify-center shrink-0">
            <svg className="h-12 w-12 -rotate-90 transform" viewBox="0 0 90 90">
              <circle
                cx="45"
                cy="45"
                r="38"
                stroke="currentColor"
                strokeWidth="7"
                fill="transparent"
                className="text-secondary"
              />
              <circle
                cx="45"
                cy="45"
                r="38"
                stroke="currentColor"
                strokeWidth="7"
                fill="transparent"
                strokeDasharray="238.7"
                strokeDashoffset={238.7 - (238.7 * healthScore) / 100}
                strokeLinecap="round"
                className={`${gaugeColor} transition-all duration-700 ease-out`}
              />
            </svg>
            <div className="absolute flex flex-col items-center justify-center text-center">
              <span className="text-xs font-bold tracking-tight text-primary-text leading-none font-mono">
                {healthScore}
              </span>
            </div>
          </div>

          <div>
            <div className="flex items-center gap-1.5">
              <h4 className="text-xs font-bold text-primary-text">
                Transaction Health Score
              </h4>
              <Badge variant="neutral" className="text-[10px] px-1 py-0">
                <ShieldCheck className="h-2.5 w-2.5 text-success mr-0.5" />
                Audited
              </Badge>
            </div>
            <p className="text-[11px] text-secondary-text mt-0.5">
              {healthScore >= 80
                ? 'High compliance — low risk detected'
                : 'Attention needed on unverified terms'}
            </p>
          </div>
        </div>

        <Button
          variant="outline"
          size="xs"
          onClick={() => setShowBriefModal(true)}
          className="shrink-0 font-medium"
        >
          <FileText className="h-3 w-3 mr-1 text-secondary-text" />
          <span>Export Brief</span>
        </Button>
      </div>

      {/* Executive Summary */}
      <div className="rounded-md border border-border bg-secondary/30 p-3.5 space-y-1.5">
        <div className="flex items-center gap-1.5">
          <Sparkles className="h-3.5 w-3.5 text-accent" />
          <h3 className="text-xs font-bold text-primary-text uppercase tracking-wider">
            Executive Brief
          </h3>
        </div>
        <p className="text-xs leading-relaxed text-primary-text">
          {summary.executiveSummary}
        </p>
      </div>

      {/* Risk Matrix */}
      {summary.riskMatrix.length > 0 && (
        <div className="rounded-md border border-border bg-surface p-3.5 space-y-2.5 shadow-2xs">
          <div className="flex items-center gap-1.5">
            <AlertTriangle className="h-3.5 w-3.5 text-warning" />
            <h3 className="text-xs font-bold text-primary-text uppercase tracking-wider">
              Identified Contract Risks ({summary.riskMatrix.length})
            </h3>
          </div>

          <div className="space-y-2">
            {summary.riskMatrix.map((risk, idx) => (
              <div
                key={idx}
                className={`p-2.5 rounded border text-xs ${
                  risk.severity === 'high'
                    ? 'border-danger-border bg-danger-light text-danger'
                    : 'border-warning-border bg-warning-light text-warning'
                }`}
              >
                <div className="flex items-center justify-between font-semibold">
                  <span>{risk.title}</span>
                  <Badge variant={risk.severity === 'high' ? 'danger' : 'warning'} className="text-[9px] uppercase px-1 py-0">
                    {risk.severity}
                  </Badge>
                </div>
                <p className="mt-1 text-primary-text text-[11px] leading-relaxed">{risk.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Contingency Matrix */}
      <div className="rounded-md border border-border bg-surface overflow-hidden shadow-2xs">
        <div className="p-3 border-b border-border flex items-center justify-between">
          <h3 className="text-xs font-bold text-primary-text uppercase tracking-wider">
            Contingency Milestones ({summary.contingencyMatrix.length})
          </h3>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-secondary-text">
            <thead className="bg-background text-primary-text border-b border-border text-[11px]">
              <tr>
                <th className="py-2 px-3 font-semibold">Contingency</th>
                <th className="py-2 px-3 font-semibold">Target Date</th>
                <th className="py-2 px-3 font-semibold">Source</th>
                <th className="py-2 px-3 font-semibold text-right">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {summary.contingencyMatrix.map((item, idx) => (
                <tr key={idx} className="hover:bg-secondary/40 transition-colors">
                  <td className="py-2 px-3 font-semibold text-primary-text">{item.label}</td>
                  <td className="py-2 px-3 font-mono text-[11px] text-primary-text font-medium">{item.targetDate}</td>
                  <td className="py-2 px-3 text-secondary-text truncate max-w-[140px] text-[11px]">
                    {item.sourceDocument ? (
                      <span>
                        {item.sourceDocument} {item.pageNumber ? `(P.${item.pageNumber})` : ''}
                      </span>
                    ) : (
                      '—'
                    )}
                  </td>
                  <td className="py-2 px-3 text-right">
                    {item.isConfirmed ? (
                      <Badge variant="success" className="text-[10px] px-1.5 py-0">
                        <CheckCircle2 className="h-2.5 w-2.5 mr-0.5" />
                        Verified
                      </Badge>
                    ) : (
                      <Badge variant="warning" className="text-[10px] px-1.5 py-0">
                        <Clock className="h-2.5 w-2.5 mr-0.5" />
                        Pending
                      </Badge>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Export Executive Brief Modal */}
      {showBriefModal && (
        <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-2xs flex items-center justify-center p-4">
          <div className="bg-surface rounded-lg shadow-xl max-w-lg w-full overflow-hidden border border-border">
            <div className="flex items-center justify-between px-5 py-3.5 border-b border-border bg-secondary/30">
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-primary-text" />
                <h3 className="text-sm font-bold text-primary-text">Executive Deal Brief</h3>
              </div>
              <button
                type="button"
                onClick={() => setShowBriefModal(false)}
                className="text-secondary-text hover:text-primary-text cursor-pointer"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="p-4 space-y-3 max-h-[60vh] overflow-y-auto">
              <div className="p-3 bg-secondary/60 text-primary-text rounded border border-border font-mono text-[11px] leading-relaxed whitespace-pre-wrap select-all">
                {generateMarkdownBrief()}
              </div>
            </div>

            <div className="flex items-center justify-between px-5 py-3 bg-secondary/20 border-t border-border">
              <span className="text-[11px] text-secondary-text">Ready to share</span>
              <div className="flex items-center gap-2">
                <Button variant="outline" size="xs" onClick={handleDownloadBrief}>
                  <Download className="h-3 w-3 mr-1" />
                  <span>Download .md</span>
                </Button>
                <Button variant="default" size="xs" onClick={handleCopyBrief}>
                  {copied ? (
                    <>
                      <Check className="h-3 w-3 mr-1" />
                      <span>Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="h-3 w-3 mr-1" />
                      <span>Copy Brief</span>
                    </>
                  )}
                </Button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
